/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Mime;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using Synesthesias.PLATEAU.Snap.Generated.Model;

namespace Synesthesias.PLATEAU.Snap.Generated.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImagesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// 撮影した建物面の画像を登録します。
        /// </summary>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <returns>BuildingImageResponse</returns>
        BuildingImageResponse CreateBuildingImageAsync(FileParameter file, string metadata);

        /// <summary>
        /// 撮影した建物面の画像を登録します。
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <returns>ApiResponse of BuildingImageResponse</returns>
        ApiResponse<BuildingImageResponse> CreateBuildingImageAsyncWithHttpInfo(FileParameter file, string metadata);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImagesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// 撮影した建物面の画像を登録します。
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuildingImageResponse</returns>
        System.Threading.Tasks.Task<BuildingImageResponse> CreateBuildingImageAsyncAsync(FileParameter file, string metadata, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));

        /// <summary>
        /// 撮影した建物面の画像を登録します。
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuildingImageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BuildingImageResponse>> CreateBuildingImageAsyncWithHttpInfoAsync(FileParameter file, string metadata, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IImagesApi : IImagesApiSync, IImagesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class ImagesApi : IDisposable, IImagesApi
    {
        private Synesthesias.PLATEAU.Snap.Generated.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <returns></returns>
        public ImagesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        public ImagesApi(string basePath)
        {
            this.Configuration = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.MergeConfigurations(
                Synesthesias.PLATEAU.Snap.Generated.Client.GlobalConfiguration.Instance,
                new Synesthesias.PLATEAU.Snap.Generated.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Synesthesias.PLATEAU.Snap.Generated.Client.ApiClient(this.Configuration.BasePath);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class using Configuration object.
        /// **IMPORTANT** This will also create an instance of HttpClient, which is less than ideal.
        /// It's better to reuse the <see href="https://docs.microsoft.com/en-us/dotnet/architecture/microservices/implement-resilient-applications/use-httpclientfactory-to-implement-resilient-http-requests#issues-with-the-original-httpclient-class-available-in-net">HttpClient and HttpClientHandler</see>.
        /// </summary>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        public ImagesApi(Synesthesias.PLATEAU.Snap.Generated.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.MergeConfigurations(
                Synesthesias.PLATEAU.Snap.Generated.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Synesthesias.PLATEAU.Snap.Generated.Client.ApiClient(this.Configuration.BasePath);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImagesApi(HttpClient client, HttpClientHandler handler = null) : this(client, (string)null, handler)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="basePath">The target service's base path in URL format.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <exception cref="ArgumentException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImagesApi(HttpClient client, string basePath, HttpClientHandler handler = null)
        {
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.MergeConfigurations(
                Synesthesias.PLATEAU.Snap.Generated.Client.GlobalConfiguration.Instance,
                new Synesthesias.PLATEAU.Snap.Generated.Client.Configuration { BasePath = basePath }
            );
            this.ApiClient = new Synesthesias.PLATEAU.Snap.Generated.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client =  this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            this.ExceptionFactory = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class using Configuration object.
        /// </summary>
        /// <param name="client">An instance of HttpClient.</param>
        /// <param name="configuration">An instance of Configuration.</param>
        /// <param name="handler">An optional instance of HttpClientHandler that is used by HttpClient.</param>
        /// <exception cref="ArgumentNullException"></exception>
        /// <returns></returns>
        /// <remarks>
        /// Some configuration settings will not be applied without passing an HttpClientHandler.
        /// The features affected are: Setting and Retrieving Cookies, Client Certificates, Proxy settings.
        /// </remarks>
        public ImagesApi(HttpClient client, Synesthesias.PLATEAU.Snap.Generated.Client.Configuration configuration, HttpClientHandler handler = null)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");
            if (client == null) throw new ArgumentNullException("client");

            this.Configuration = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.MergeConfigurations(
                Synesthesias.PLATEAU.Snap.Generated.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.ApiClient = new Synesthesias.PLATEAU.Snap.Generated.Client.ApiClient(client, this.Configuration.BasePath, handler);
            this.Client = this.ApiClient;
            this.AsynchronousClient = this.ApiClient;
            ExceptionFactory = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="ImagesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public ImagesApi(Synesthesias.PLATEAU.Snap.Generated.Client.ISynchronousClient client, Synesthesias.PLATEAU.Snap.Generated.Client.IAsynchronousClient asyncClient, Synesthesias.PLATEAU.Snap.Generated.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = Synesthesias.PLATEAU.Snap.Generated.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Disposes resources if they were created by us
        /// </summary>
        public void Dispose()
        {
            this.ApiClient?.Dispose();
        }

        /// <summary>
        /// Holds the ApiClient if created
        /// </summary>
        public Synesthesias.PLATEAU.Snap.Generated.Client.ApiClient ApiClient { get; set; } = null;

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public Synesthesias.PLATEAU.Snap.Generated.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public Synesthesias.PLATEAU.Snap.Generated.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public Synesthesias.PLATEAU.Snap.Generated.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public Synesthesias.PLATEAU.Snap.Generated.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// 撮影した建物面の画像を登録します。 
        /// </summary>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <returns>BuildingImageResponse</returns>
        public BuildingImageResponse CreateBuildingImageAsync(FileParameter file, string metadata)
        {
            Synesthesias.PLATEAU.Snap.Generated.Client.ApiResponse<BuildingImageResponse> localVarResponse = CreateBuildingImageAsyncWithHttpInfo(file, metadata);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 撮影した建物面の画像を登録します。 
        /// </summary>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <returns>ApiResponse of BuildingImageResponse</returns>
        public Synesthesias.PLATEAU.Snap.Generated.Client.ApiResponse<BuildingImageResponse> CreateBuildingImageAsyncWithHttpInfo(FileParameter file, string metadata)
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new Synesthesias.PLATEAU.Snap.Generated.Client.ApiException(400, "Missing required parameter 'file' when calling ImagesApi->CreateBuildingImageAsync");

            // verify the required parameter 'metadata' is set
            if (metadata == null)
                throw new Synesthesias.PLATEAU.Snap.Generated.Client.ApiException(400, "Missing required parameter 'metadata' when calling ImagesApi->CreateBuildingImageAsync");

            Synesthesias.PLATEAU.Snap.Generated.Client.RequestOptions localVarRequestOptions = new Synesthesias.PLATEAU.Snap.Generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("File", file);
            localVarRequestOptions.FormParameters.Add("Metadata", Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.ParameterToString(metadata)); // form parameter


            // make the HTTP request
            var localVarResponse = this.Client.Post<BuildingImageResponse>("/api/building-image", localVarRequestOptions, this.Configuration);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateBuildingImageAsync", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

        /// <summary>
        /// 撮影した建物面の画像を登録します。 
        /// </summary>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BuildingImageResponse</returns>
        public async System.Threading.Tasks.Task<BuildingImageResponse> CreateBuildingImageAsyncAsync(FileParameter file, string metadata, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            Synesthesias.PLATEAU.Snap.Generated.Client.ApiResponse<BuildingImageResponse> localVarResponse = await CreateBuildingImageAsyncWithHttpInfoAsync(file, metadata, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// 撮影した建物面の画像を登録します。 
        /// </summary>
        /// <exception cref="Synesthesias.PLATEAU.Snap.Generated.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="file">建物面を撮影した画像ファイル</param>
        /// <param name="metadata">画像に関連するメタデータ</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BuildingImageResponse)</returns>
        public async System.Threading.Tasks.Task<Synesthesias.PLATEAU.Snap.Generated.Client.ApiResponse<BuildingImageResponse>> CreateBuildingImageAsyncWithHttpInfoAsync(FileParameter file, string metadata, System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
        {
            // verify the required parameter 'file' is set
            if (file == null)
                throw new Synesthesias.PLATEAU.Snap.Generated.Client.ApiException(400, "Missing required parameter 'file' when calling ImagesApi->CreateBuildingImageAsync");

            // verify the required parameter 'metadata' is set
            if (metadata == null)
                throw new Synesthesias.PLATEAU.Snap.Generated.Client.ApiException(400, "Missing required parameter 'metadata' when calling ImagesApi->CreateBuildingImageAsync");


            Synesthesias.PLATEAU.Snap.Generated.Client.RequestOptions localVarRequestOptions = new Synesthesias.PLATEAU.Snap.Generated.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "multipart/form-data"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };


            var localVarContentType = Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null) localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);

            var localVarAccept = Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null) localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);

            localVarRequestOptions.FileParameters.Add("File", file);
            localVarRequestOptions.FormParameters.Add("Metadata", Synesthesias.PLATEAU.Snap.Generated.Client.ClientUtils.ParameterToString(metadata)); // form parameter


            // make the HTTP request

            var localVarResponse = await this.AsynchronousClient.PostAsync<BuildingImageResponse>("/api/building-image", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateBuildingImageAsync", localVarResponse);
                if (_exception != null) throw _exception;
            }

            return localVarResponse;
        }

    }
}
