/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing BuildingImageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuildingImageResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuildingImageResponse
        //private BuildingImageResponse instance;

        public BuildingImageResponseTests()
        {
            // TODO uncomment below to create an instance of BuildingImageResponse
            //instance = new BuildingImageResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuildingImageResponse
        /// </summary>
        [Fact]
        public void BuildingImageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuildingImageResponse
            //Assert.IsType<BuildingImageResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Status'
        /// </summary>
        [Fact]
        public void StatusTest()
        {
            // TODO unit test for the property 'Status'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
