/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing Coordinate
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CoordinateTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Coordinate
        //private Coordinate instance;

        public CoordinateTests()
        {
            // TODO uncomment below to create an instance of Coordinate
            //instance = new Coordinate();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Coordinate
        /// </summary>
        [Fact]
        public void CoordinateInstanceTest()
        {
            // TODO uncomment below to test "IsType" Coordinate
            //Assert.IsType<Coordinate>(instance);
        }

        /// <summary>
        /// Test the property 'Longitude'
        /// </summary>
        [Fact]
        public void LongitudeTest()
        {
            // TODO unit test for the property 'Longitude'
        }

        /// <summary>
        /// Test the property 'Latitude'
        /// </summary>
        [Fact]
        public void LatitudeTest()
        {
            // TODO unit test for the property 'Latitude'
        }

        /// <summary>
        /// Test the property 'Altitude'
        /// </summary>
        [Fact]
        public void AltitudeTest()
        {
            // TODO unit test for the property 'Altitude'
        }
    }
}
