/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing StatusType
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StatusTypeTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StatusType
        //private StatusType instance;

        public StatusTypeTests()
        {
            // TODO uncomment below to create an instance of StatusType
            //instance = new StatusType();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StatusType
        /// </summary>
        [Fact]
        public void StatusTypeInstanceTest()
        {
            // TODO uncomment below to test "IsType" StatusType
            //Assert.IsType<StatusType>(instance);
        }
    }
}
