/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing Surface
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SurfaceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Surface
        //private Surface instance;

        public SurfaceTests()
        {
            // TODO uncomment below to create an instance of Surface
            //instance = new Surface();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Surface
        /// </summary>
        [Fact]
        public void SurfaceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Surface
            //Assert.IsType<Surface>(instance);
        }

        /// <summary>
        /// Test the property 'Gmlid'
        /// </summary>
        [Fact]
        public void GmlidTest()
        {
            // TODO unit test for the property 'Gmlid'
        }

        /// <summary>
        /// Test the property 'Coordinates'
        /// </summary>
        [Fact]
        public void CoordinatesTest()
        {
            // TODO unit test for the property 'Coordinates'
        }
    }
}
