/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing VisibleSurfacesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VisibleSurfacesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VisibleSurfacesResponse
        //private VisibleSurfacesResponse instance;

        public VisibleSurfacesResponseTests()
        {
            // TODO uncomment below to create an instance of VisibleSurfacesResponse
            //instance = new VisibleSurfacesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VisibleSurfacesResponse
        /// </summary>
        [Fact]
        public void VisibleSurfacesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" VisibleSurfacesResponse
            //Assert.IsType<VisibleSurfacesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Surfaces'
        /// </summary>
        [Fact]
        public void SurfacesTest()
        {
            // TODO unit test for the property 'Surfaces'
        }
    }
}
