/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Synesthesias.PLATEAU.Snap.Generated.Model;
using Synesthesias.PLATEAU.Snap.Generated.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Model
{
    /// <summary>
    ///  Class for testing VisibleSurfacesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VisibleSurfacesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VisibleSurfacesRequest
        //private VisibleSurfacesRequest instance;

        public VisibleSurfacesRequestTests()
        {
            // TODO uncomment below to create an instance of VisibleSurfacesRequest
            //instance = new VisibleSurfacesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VisibleSurfacesRequest
        /// </summary>
        [Fact]
        public void VisibleSurfacesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" VisibleSurfacesRequest
            //Assert.IsType<VisibleSurfacesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'From'
        /// </summary>
        [Fact]
        public void FromTest()
        {
            // TODO unit test for the property 'From'
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Roll'
        /// </summary>
        [Fact]
        public void RollTest()
        {
            // TODO unit test for the property 'Roll'
        }

        /// <summary>
        /// Test the property 'MaxDistance'
        /// </summary>
        [Fact]
        public void MaxDistanceTest()
        {
            // TODO unit test for the property 'MaxDistance'
        }

        /// <summary>
        /// Test the property 'FieldOfView'
        /// </summary>
        [Fact]
        public void FieldOfViewTest()
        {
            // TODO unit test for the property 'FieldOfView'
        }
    }
}
