/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Synesthesias.PLATEAU.Snap.Generated.Client;
using Synesthesias.PLATEAU.Snap.Generated.Api;
// uncomment below to import models
//using Synesthesias.PLATEAU.Snap.Generated.Model;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Api
{
    /// <summary>
    ///  Class for testing ImagesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ImagesApiTests : IDisposable
    {
        private ImagesApi instance;

        public ImagesApiTests()
        {
            instance = new ImagesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ImagesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ImagesApi
            //Assert.IsType<ImagesApi>(instance);
        }

        /// <summary>
        /// Test CreateBuildingImageAsync
        /// </summary>
        [Fact]
        public void CreateBuildingImageAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //FileParameter file = null;
            //string metadata = null;
            //var response = instance.CreateBuildingImageAsync(file, metadata);
            //Assert.IsType<BuildingImageResponse>(response);
        }
    }
}
