/*
 * PLATEAU.Snap.Server
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using Synesthesias.PLATEAU.Snap.Generated.Client;
using Synesthesias.PLATEAU.Snap.Generated.Api;
// uncomment below to import models
//using Synesthesias.PLATEAU.Snap.Generated.Model;

namespace Synesthesias.PLATEAU.Snap.Generated.Test.Api
{
    /// <summary>
    ///  Class for testing SurfacesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class SurfacesApiTests : IDisposable
    {
        private SurfacesApi instance;

        public SurfacesApiTests()
        {
            instance = new SurfacesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SurfacesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' SurfacesApi
            //Assert.IsType<SurfacesApi>(instance);
        }

        /// <summary>
        /// Test GetVisibleSurfacesAsync
        /// </summary>
        [Fact]
        public void GetVisibleSurfacesAsyncTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //VisibleSurfacesRequest visibleSurfacesRequest = null;
            //var response = instance.GetVisibleSurfacesAsync(visibleSurfacesRequest);
            //Assert.IsType<VisibleSurfacesResponse>(response);
        }
    }
}
