name: ドキュメント自動デプロイ

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    name: GitHub Pages へデプロイ
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: .NET をセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - run: dotnet tool update -g docfx

      - name: ドキュメントをビルド
        run: docfx docs/docfx.json

      - name: docs ディレクトリの変更をコミット＆プッシュ
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/
          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "docs: [ドキュメント自動更新]"
          git push origin main

      - name: 「gh-pages」に「docs/_site」の内容をデプロイ
        run: |
          git fetch origin gh-pages || echo "gh-pagesブランチが見つかりませんでした"
          git switch --orphan gh-pages
          git reset --hard
          git checkout main -- docs/_site
          mv docs/_site/* .
          rm -rf docs
          git commit -m "docs: [GitHub Pages自動更新]"
          git push --force origin gh-pages
          git checkout main

      - name: アーティファクトをアップロード
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs/_site'

      - name: GitHub Pages へデプロイ
        id: deployment
        uses: actions/deploy-pages@v4