name: ドキュメント自動デプロイ

on:
  push:
    branches:
      - main

permissions:
  contents: write
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  publish-docs:
    name: GitHub Pages へデプロイ
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: .NET をセットアップ
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x

      - name: DocFX をインストール
        run: dotnet tool update -g docfx

      - name: ドキュメントをビルド
        run: docfx docs/docfx.json

      - name: gh-pages ブランチを作成 or リセット
        run: |
          git fetch origin gh-pages || echo "gh-pages does not exist yet"
          git switch --orphan gh-pages
          git reset --hard

      - name: docs/_site の内容をコピー
        run: cp -r docs/_site/* .

      - name: docs の内容を削除
        run: rm -rf docs

      - name: 変更をコミット
        run: |
          git add --all
          git commit -m "docs: [GitHub Pages自動更新]"

      - name: gh-pages に強制プッシュ
        run: git push --force origin gh-pages